### ISSUE TITLE
After install won't run

### ISSUE THREAD

**Issue by marko-mlinarevic** [TheGiddyLimit/TheGiddyLimit.github.io#304]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: After npm install it won't run says utils.js is missing

Page(s) affected: Entire app

Reproduction steps:

Additional information: 

```
Error: Cannot find module '../js/utils'
Require stack:
- E:\node-projects\5eTools\node\clean-jsons.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (E:\node-projects\5eTools\node\clean-jsons.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'E:\\node-projects\\5eTools\\node\\clean-jsons.js' ]
}
```

Browser (Chromium, Firefox, Edge, etc): Chrome

Platform (Windows, iOS, Android, etc): Windows 10

**Comment by TheGiddyLimit** [comment]
Sorry, what commands are you running, here? Just `npm install`?

**Comment by marko-mlinarevic** [comment]
sry, I should have been more specific. Npm install passes, but other like build i dev toss out this error

**Comment by TheGiddyLimit** [comment]
Curious, it works fine for me. What versions of Node/NPM do you have? Where are you running the commands from?

**Comment by marko-mlinarevic** [comment]
I found out was the problem. When I donwloaded from this link node modules are in it and it wont run. I needed to delete node_modules and npm install again and it works 
https://get.5e.tools/release/5eTools.1.102.7.zip
